# Generated by Django 4.2 on 2023-08-06 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_questions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
