# Generated by Django 4.2 on 2023-08-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_questions_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='create_date',
            new_name='createddate',
        ),
    ]
